sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.3

script:
  - if [[ $TRAVIS_PHP_VERSION == "5.5" ]]; then make test-coveralls; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "5.5" ]]; then composer require satooshi/php-coveralls; fi
  - if [[ $TRAVIS_PHP_VERSION == "5.5" ]]; then php vendor/bin/php-coveralls -v; fi
